INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (1, N'Zygmunt Freud', 1)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (2, N'J.R.R Tolkien', 1)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (3, N'Winston Churchill', 1)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (4, N'Adolf Hitler', 1)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (5, N'Era Nowe Horyzonty we Wroc³awiu', 2)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (6, N'Dwa Brzegi w Janowcu i Kazimierzu', 2)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (7, N'Lubuskie Lato w £agowie', 2)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (8, N'Malta Festiwal Poznañ', 2)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (9, N'Don Giovanni', 3)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (10, N'Carmen', 3)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (11, N'Aida', 3)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (12, N'Turandot', 3)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (13, N'Fiat 126p', 4)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (14, N'Polonez', 4)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (15, N'Syrena', 4)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (16, N'Warszawa', 4)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (17, N'Poniedzia³ek', 5)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (18, N'Czwartek', 5)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (19, N'Sobotê', 5)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (20, N'Niedzielê', 5)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (21, N'Tygrysa', 6)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (22, N'Królika', 6)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (23, N'Szczura', 6)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (24, N'Wê¿a', 6)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (25, N'AC/DC', 7)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (26, N'Pink Floyd', 7)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (27, N'Rolling Stones', 7)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (28, N'The Beatles', 7)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (29, N'5,56mm', 8)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (30, N'6,35mm', 8)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (31, N'7,62mm', 8)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (32, N'0,44cala', 8)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (33, N'O obrotach sfer niebieskich', 9)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (34, N'Rozprawa o metodzie', 9)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (35, N'O powstawaniu gatunków', 9)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (36, N'Samolubny gen ', 9)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (37, N'Pele', 10)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (38, N'Diego Maradona', 10)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (39, N'Lionel Messi', 10)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (40, N'Cristiano Ronaldo', 10)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (41, N'Ga³ka lodów œmietankowych(25g)', 11)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (42, N'Kieliszek koniaku(40ml))', 11)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (43, N'Pomarañcza(150g)', 11)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (44, N'Jajko na twardo', 11)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (45, N'Koœcio³y', 12)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (46, N'Pa³ace', 12)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (47, N'Aleje', 12)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (48, N'Mosty', 12)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (49, N'Andrzej Go³ota', 13)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (50, N'Jerzy Kulej', 13)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (51, N'Przemys³aw Saleta', 13)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (52, N'Tomasz Adamek', 13)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (53, N'30m na 10m', 14)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (54, N'45m na 12m', 14)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (55, N'105m na 68m', 14)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (56, N'300m na 150m', 14)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (57, N'Herkules Poirot', 15)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (58, N'Arsene Lupin', 15)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (59, N'Janosik', 15)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (60, N'Philip Marlowe', 15)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (61, N'Dop³ywy orinoko', 16)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (62, N'Ryby raf koralowych', 16)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (63, N'Jednostki monetarne', 16)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (64, N'Imiona hobbitów', 16)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (65, N'B³onnika', 17)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (66, N'Bia³ek', 17)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (67, N'Wêglowodanów', 17)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (68, N'T³uszczy', 17)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (69, N'Stanów Zjednoczonych', 18)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (70, N'Wielkiej Brytanii', 18)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (71, N'Chiñskiej Republiki Ludowej', 18)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (72, N'Francji', 18)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (73, N'Turcja', 19)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (74, N'Szwecja', 19)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (75, N'Wêgry', 19)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (76, N'Niderlandy', 19)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (77, N'z Rosj¹', 20)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (78, N'z Ukrain¹', 20)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (79, N'ze S³owacj¹', 20)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (80, N'z Czechami', 20)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (81, N'Porucznik Columbo', 22)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (82, N'Porucznik Kojak', 22)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (83, N'Detektyw Wallander', 22)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (84, N'Detektyw Monk', 22)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (85, N'Bogurodzica', 21)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (86, N'Rota', 21)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (87, N'Bo¿e, coœ Polskê...', 21)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (88, N'Gaude mater Polonia', 21)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (89, N'Jelito grube', 23)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (90, N'Jelito cienkie', 23)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (91, N'Rdzeñ krêgowy', 23)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (92, N'¯y³a wrotna', 23)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (93, N'Po³udniowo-amerykañski ssak drapie¿ny', 24)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (94, N'Cieœnina w archipegu malajskim', 24)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (95, N'Luksusowa kawa', 24)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (96, N'Roœlina ozdobna', 24)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (97, N'iPad', 25)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (98, N'iPhone', 25)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (99, N'iPod', 25)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (100, N'iBook', 25)
GO
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (101, N'Neonu', 27)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (102, N'Argonu', 27)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (103, N'Dwutlenku Wêgla', 27)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (104, N'Ozonu', 27)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (105, N'1977', 26)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (106, N'1979', 26)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (107, N'1982', 26)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (108, N'1985', 26)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (109, N'w Los Angeles', 28)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (110, N'w Chicago', 28)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (111, N'w Nowym Jorku', 28)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (112, N'w Miami', 28)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (113, N'8', 29)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (114, N'5', 29)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (115, N'4', 29)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (116, N'2', 29)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (117, N'Ameryka Po³udniowa', 30)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (118, N'Azja', 30)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (119, N'Afryka', 30)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (120, N'Australia z Oceani¹', 30)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (121, N'RPA', 31)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (122, N'Kanada', 31)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (123, N'Australia', 31)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (124, N'Brazylia', 31)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (125, N'Jose van Dam', 32)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (126, N'Mariusz Kwiecieñ', 32)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (127, N'Andreas Scholl', 32)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (128, N'Andrea Bocelli', 32)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (129, N'Litewski', 33)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (130, N'Œl¹ski', 33)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (131, N'Karaimski', 33)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (132, N'Kaszubski', 33)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (133, N'Kwartet smyczkowy', 34)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (134, N'Kwintet wokalny', 34)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (135, N'Sekstet denty', 34)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (136, N'Tercet egzotyczny', 34)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (137, N'Cholera', 35)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (138, N'D¿uma', 35)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (139, N'Tyfus', 35)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (140, N'Grypa', 35)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (141, N'Wzi¹œæ', 36)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (142, N'Wzi¹æ', 36)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (143, N'Wzioñæ', 36)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (144, N'Wzi¹Ÿæ', 36)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (145, N'Dziadek do orzechów', 37)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (146, N'Ognisty ptak', 37)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (147, N'Kopciuszek', 37)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (148, N'Jezioro ³abêdzie', 37)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (149, N'Koc', 38)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (150, N'Wyrko', 38)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (151, N'Wino', 38)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (152, N'Chata', 38)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (153, N'Gregory', 39)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (154, N'George', 39)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (155, N'Arthur', 39)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (156, N'John', 39)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (157, N'Hildegarda', 40)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (158, N'Hermenegilda', 40)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (159, N'Beneficja', 40)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (160, N'Benedykta', 40)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (161, N'Edward No¿ycorêki', 41)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (162, N'Kapitan Jack Sparrow', 41)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (163, N'Donny Brasco', 41)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (164, N'Juliette Binoche', 42)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (165, N'Irene Jacob', 42)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (166, N'Odri Tatto', 42)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (167, N'Dynamit', 43)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (168, N'Telefon', 43)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (169, N'Szczepionka przeciw ospie', 43)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (170, N'Architekci', 44)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (171, N'Lekkoatleci', 44)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (172, N'Literaci', 44)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (173, N'20 z³', 45)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (174, N'100 z³', 45)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (175, N'200 z³', 45)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (176, N'Czerwony', 46)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (177, N'Czarny', 46)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (178, N'Bia³y', 46)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (179, N'Pink Floyd', 47)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (180, N'The Doors', 47)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (181, N'The Rolling Stones', 47)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (182, N'Bee Gees', 48)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (183, N'U2', 48)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (184, N'ABBA', 48)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (185, N'Mieszaniem drinków', 49)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (186, N'Parzeniem kawy', 49)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (187, N'Leczeniem oty³oœci', 49)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (188, N'Dziennikarzom', 50)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (189, N'Biznesmenom', 50)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (190, N'Urzêdnikom', 50)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (191, N'Kobiet', 51)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (192, N'Mê¿czyzn', 51)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (193, N'Allo, allo', 52)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (194, N'Domek na prerii', 52)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (195, N'Przed czterdziestk¹', 53)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (196, N'Po czterdziestce', 53)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (197, N'6 godz. 11 minut', 54)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (198, N'11 godz. 5 minut', 54)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (199, N'44 mln ton', 56)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (200, N'440 mln ton', 56)
GO
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (201, N'1990', 57)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (202, N'1986', 57)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (203, N'Janet Jackson', 58)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (204, N'Whitney Houston', 58)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (205, N'Pawe³', 59)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (206, N'Gawe³', 59)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (207, N'Pierwsza kobieta polecia³a w kosmos', 60)
INSERT [dbo].[Answers] ([AnswerId], [AnswerName], [QuestionId]) VALUES (208, N'W zamachu zgin¹³ John Kennedy', 60)
GO
INSERT [dbo].[Player] ([PlayerId], [Surname], [Name], [Points]) VALUES (1, N'Magdziak', N'Mateusz', 650000)
GO
INSERT [dbo].[Questions] ([QuestionId], [QuestionCategory], [QuestionName], [CorrectAnswer], [QuestionLevel]) VALUES (1, N'Fajka', N'Który z nich by³ namiêtnym palaczem fajki?', N'J.R.R. Tolkien', 4)
INSERT [dbo].[Questions] ([QuestionId], [QuestionCategory], [QuestionName], [CorrectAnswer], [QuestionLevel]) VALUES (2, N'Festiwale', N'Który z tych letnich polskich festiwali nie jest festiwalem filmowym?', N'Malta Festival Poznañ', 4)
INSERT [dbo].[Questions] ([QuestionId], [QuestionCategory], [QuestionName], [CorrectAnswer], [QuestionLevel]) VALUES (3, N'Aria', N'Pieœñ torleadora s³ynna aria barytonowa, pochodzi z opery:', N'Carmen', 4)
INSERT [dbo].[Questions] ([QuestionId], [QuestionCategory], [QuestionName], [CorrectAnswer], [QuestionLevel]) VALUES (4, N'Auta', N'Produkcja którego z tych polskich aut zaczê³a siê najpóŸniej?', N'Polonez', 4)
INSERT [dbo].[Questions] ([QuestionId], [QuestionCategory], [QuestionName], [CorrectAnswer], [QuestionLevel]) VALUES (5, N'Kalendarz', N'Jeœli w danym miesi¹cu 13-sty wypada w pi¹tek, to 1-szy w:', N'Niedzielê', 4)
INSERT [dbo].[Questions] ([QuestionId], [QuestionCategory], [QuestionName], [CorrectAnswer], [QuestionLevel]) VALUES (6, N'Kalendarz', N'Trzeci lutego 2011r. chiñczycy œwiêtowali nowy rok. Rozpocz¹³ siê rok:', N'Królika', 4)
INSERT [dbo].[Questions] ([QuestionId], [QuestionCategory], [QuestionName], [CorrectAnswer], [QuestionLevel]) VALUES (7, N'Kapele', N'Która z tych kultowych grup nie powsta³a w Wielkiej Brytanii?', N'AC/DC', 4)
INSERT [dbo].[Questions] ([QuestionId], [QuestionCategory], [QuestionName], [CorrectAnswer], [QuestionLevel]) VALUES (8, N'Kaliber', N'Jaki jest kaliber karabinka AK tzw. ka³asznikowa?', N'7,62mm', 4)
INSERT [dbo].[Questions] ([QuestionId], [QuestionCategory], [QuestionName], [CorrectAnswer], [QuestionLevel]) VALUES (9, N'Dzie³o', N'Prze³omowe dzie³o naukowe Karola Darwina nosi³o tytu³:', N'O powstawaniu gatunków', 4)
INSERT [dbo].[Questions] ([QuestionId], [QuestionCategory], [QuestionName], [CorrectAnswer], [QuestionLevel]) VALUES (10, N'Dziesi¹tka', N'Który z tych pi³karzy nie gra³ z "magicznym" numerem 10 na koszulce?', N'Cristiano Ronaldo', 4)
INSERT [dbo].[Questions] ([QuestionId], [QuestionCategory], [QuestionName], [CorrectAnswer], [QuestionLevel]) VALUES (11, N'Energia', N'Co ma najwiêcej kalorii?', N'Ga³ka lodów œmietankowych(25g)', 4)
INSERT [dbo].[Questions] ([QuestionId], [QuestionCategory], [QuestionName], [CorrectAnswer], [QuestionLevel]) VALUES (12, N'Europejskie Stolice', N'Chudy, Karola, El¿biety, Poniatowskiego, Vasco da gamy, Wymiany. O jakie obiekty chodzi?', N'Mosty', 4)
INSERT [dbo].[Questions] ([QuestionId], [QuestionCategory], [QuestionName], [CorrectAnswer], [QuestionLevel]) VALUES (13, N'Boks', N'Pierwszym w historii polskim bokserem, który zdoby³ pas mistrza œwiata, przyznawany przez magazyn "The Ring", by³:', N'Tomasz Adamek', 4)
INSERT [dbo].[Questions] ([QuestionId], [QuestionCategory], [QuestionName], [CorrectAnswer], [QuestionLevel]) VALUES (14, N'Boisko', N'Boisko do pi³ki no¿nej do rozgrywania meczów miêdzynarodowych powinno mieæ wymiary:', N'105m na 68m', 4)
INSERT [dbo].[Questions] ([QuestionId], [QuestionCategory], [QuestionName], [CorrectAnswer], [QuestionLevel]) VALUES (15, N'D¿entelmen', N'Powieœciowo-serialowy d¿entelmen-w³amywacz nazywa³ siê:', N'Arsene Lupin', 4)
INSERT [dbo].[Questions] ([QuestionId], [QuestionCategory], [QuestionName], [CorrectAnswer], [QuestionLevel]) VALUES (16, N'Dziwne S³owa', N'Colón, kip, rinngit, tugrik i balboa to:', N'Jednostki monetarne', 4)
INSERT [dbo].[Questions] ([QuestionId], [QuestionCategory], [QuestionName], [CorrectAnswer], [QuestionLevel]) VALUES (17, N'Dieta', N'Popularna dieta dr Dukana polega na spo¿ywaniu przede wszystkim:', N'Bia³ek', 4)
INSERT [dbo].[Questions] ([QuestionId], [QuestionCategory], [QuestionName], [CorrectAnswer], [QuestionLevel]) VALUES (18, N'Dwiza', N'Wolnoœæ, równoœæ, braterstwo jest pañstwow¹ dewiz¹:', N'Francji', 4)
INSERT [dbo].[Questions] ([QuestionId], [QuestionCategory], [QuestionName], [CorrectAnswer], [QuestionLevel]) VALUES (19, N'Granice', N'Z którym pañstwem Polska w ponad tysi¹cletniej historii nie mia³a wspólnej granicy?', N'Niderlandy', 4)
INSERT [dbo].[Questions] ([QuestionId], [QuestionCategory], [QuestionName], [CorrectAnswer], [QuestionLevel]) VALUES (20, N'Granice', N'Z którym z tych pañstw Polska ma najd³u¿sz¹ granicê lodow¹?', N'z Czechami', 4)
INSERT [dbo].[Questions] ([QuestionId], [QuestionCategory], [QuestionName], [CorrectAnswer], [QuestionLevel]) VALUES (21, N'Dawne pieœni', N'Najstarsz¹ zachowan¹ wraz z melodi¹ polska pieœñ to:', N'Bogurodzica', 4)
INSERT [dbo].[Questions] ([QuestionId], [QuestionCategory], [QuestionName], [CorrectAnswer], [QuestionLevel]) VALUES (22, N'Detektywi', N'Który z tych serialowych detektywów by³ ³ysy jak kolano?', N'Porucznik Kojak', 4)
INSERT [dbo].[Questions] ([QuestionId], [QuestionCategory], [QuestionName], [CorrectAnswer], [QuestionLevel]) VALUES (23, N'Cia³o', N'Co jest w ciele zdrowego, doros³ego cz³owieka d³u¿sze:', N'Jelito cienkie', 4)
INSERT [dbo].[Questions] ([QuestionId], [QuestionCategory], [QuestionName], [CorrectAnswer], [QuestionLevel]) VALUES (24, N'Ciekawostki', N'Kopiluwak to:', N'Luksusowa kawa', 4)
INSERT [dbo].[Questions] ([QuestionId], [QuestionCategory], [QuestionName], [CorrectAnswer], [QuestionLevel]) VALUES (25, N'Jab³ko', N'Cienki tablet firmy Apple z ekranem dotykowym to:', N'iPad', 4)
INSERT [dbo].[Questions] ([QuestionId], [QuestionCategory], [QuestionName], [CorrectAnswer], [QuestionLevel]) VALUES (26, N'Jab³ko', N'Apple II, pierwszy na œwiecie komputer domowy pojawi³ siê w:', N'1977', 4)
INSERT [dbo].[Questions] ([QuestionId], [QuestionCategory], [QuestionName], [CorrectAnswer], [QuestionLevel]) VALUES (27, N'Gazy', N'Bior¹c pod uwagê sk³ad przeciêtny przy powierzchni ziemi, którego z tych gazów jest w suchym powietrzu najwiêcej?', N'Argonu', 4)
INSERT [dbo].[Questions] ([QuestionId], [QuestionCategory], [QuestionName], [CorrectAnswer], [QuestionLevel]) VALUES (28, N'Gdzie mieszkaj¹', N'Gdzie mieszkaj¹ tytu³owi przyjaciele?', N'w Nowym Jorku', 4)
INSERT [dbo].[Questions] ([QuestionId], [QuestionCategory], [QuestionName], [CorrectAnswer], [QuestionLevel]) VALUES (29, N'Geometria', N'Ile ramion ma trapez?', N'2', 4)
INSERT [dbo].[Questions] ([QuestionId], [QuestionCategory], [QuestionName], [CorrectAnswer], [QuestionLevel]) VALUES (30, N'Geografia', N'Kontynent, na którym znajduje siê najwy¿szy szczyt górski ziemi, to:', N'Azja', 4)
INSERT [dbo].[Questions] ([QuestionId], [QuestionCategory], [QuestionName], [CorrectAnswer], [QuestionLevel]) VALUES (31, N'Globus', N'Przez terytorium którego z tych pañstw przechodzi równik?', N'Brazylia', 4)
INSERT [dbo].[Questions] ([QuestionId], [QuestionCategory], [QuestionName], [CorrectAnswer], [QuestionLevel]) VALUES (32, N'G³os', N'Który z tych s³ynnych œpiewaków klasycznych, œpiewa kontratenorem, g³osem o skali ¿eñskiego altu', N'Andreas Scholl', 4)
INSERT [dbo].[Questions] ([QuestionId], [QuestionCategory], [QuestionName], [CorrectAnswer], [QuestionLevel]) VALUES (33, N'Jêzyki', N'Który z jêzyków u¿ywanych przez spo³ecznoœci zamieszka³e w polsce ma ustawowy status jêzyka regionalnego?', N'Kaszubski', 4)
INSERT [dbo].[Questions] ([QuestionId], [QuestionCategory], [QuestionName], [CorrectAnswer], [QuestionLevel]) VALUES (34, N'Kabaret', N'Muzycy z kabaretowej grupy MoCarta tworz¹:', N'Kwartet smyczkowy', 4)
INSERT [dbo].[Questions] ([QuestionId], [QuestionCategory], [QuestionName], [CorrectAnswer], [QuestionLevel]) VALUES (35, N'Choroba', N'Jaka znana choroba da³a tytu³ powieœci Alberta Camusa?', N'D¿uma', 4)
INSERT [dbo].[Questions] ([QuestionId], [QuestionCategory], [QuestionName], [CorrectAnswer], [QuestionLevel]) VALUES (36, N'B³êdy', N'Która z poni¿szych form zapisu wyrazu jest poprawna ortograficznie?', N'Wzi¹æ', 4)
INSERT [dbo].[Questions] ([QuestionId], [QuestionCategory], [QuestionName], [CorrectAnswer], [QuestionLevel]) VALUES (37, N'Balet', N'Historia ksiê¿niczki Odetty, zaklêtej wraz z towarzyszkami w ptaki, to kanwa którego baletu?', N'Jezioro ³abêdzie', 4)
INSERT [dbo].[Questions] ([QuestionId], [QuestionCategory], [QuestionName], [CorrectAnswer], [QuestionLevel]) VALUES (38, N'Autobiografia', N'Oprócz radia Luksemburg i szk³a niezbêdnym elementem zabawy w sobotni¹ noc wed³ug autobiografii "Perfectu" by³:', N'Chata', 4)
INSERT [dbo].[Questions] ([QuestionId], [QuestionCategory], [QuestionName], [CorrectAnswer], [QuestionLevel]) VALUES (39, N'Imiê', N'Jak mia³ na imiê powieœciowy przyjaciel Sherlocka Holmesa dr.Watson?', N'John', 4)
INSERT [dbo].[Questions] ([QuestionId], [QuestionCategory], [QuestionName], [CorrectAnswer], [QuestionLevel]) VALUES (40, N'Imiê', N'Jak mia³a na imiê Kociubiñska, bohaterka teatrzyku absurdu "Zielona Gêœ" K.I Ga³czyñskiego?', N'Hermenegilda', 4)
INSERT [dbo].[Questions] ([QuestionId], [QuestionCategory], [QuestionName], [CorrectAnswer], [QuestionLevel]) VALUES (41, N'Trzydziestka', N'W któr¹ z tych postaci Johnny Depp wcieli³ siê przed trzydziestoma urodzinami?', N'Edward No¿ycorêki', 3)
INSERT [dbo].[Questions] ([QuestionId], [QuestionCategory], [QuestionName], [CorrectAnswer], [QuestionLevel]) VALUES (42, N'Trzy kolory', N'Która francuska aktorka zagra³a we wszystkich czêœciach trylogii Kieœlowskiego "Trzy kolory".', N'Juliette Binoche', 3)
INSERT [dbo].[Questions] ([QuestionId], [QuestionCategory], [QuestionName], [CorrectAnswer], [QuestionLevel]) VALUES (43, N'Wynalazki', N'Z jakim odkryciem/wynalazkiem zwi¹zany jest Alfred Nobel?', N'Dynamit', 3)
INSERT [dbo].[Questions] ([QuestionId], [QuestionCategory], [QuestionName], [CorrectAnswer], [QuestionLevel]) VALUES (44, N'Wybitni', N'Zadie Smith, Haruki Murakani i John Coetzee to wybitni:', N'Literaci', 3)
INSERT [dbo].[Questions] ([QuestionId], [QuestionCategory], [QuestionName], [CorrectAnswer], [QuestionLevel]) VALUES (45, N'W¹sy', N'Na którym banknocie król ma w¹sy?', N'20 z³', 3)
INSERT [dbo].[Questions] ([QuestionId], [QuestionCategory], [QuestionName], [CorrectAnswer], [QuestionLevel]) VALUES (46, N'Wideoklipy', N'Jakiego koloru by³ lateksowy kostium Britney Spears w przebojowym teledysku "Oops... I did it again?"', N'Czerwony', 3)
INSERT [dbo].[Questions] ([QuestionId], [QuestionCategory], [QuestionName], [CorrectAnswer], [QuestionLevel]) VALUES (47, N'Zespo³y', N'Nazwê której grupy muzycznej wziê³a siê z inspiracji tytu³em eseju Aldousa Huxleya?', N'The Doors', 3)
INSERT [dbo].[Questions] ([QuestionId], [QuestionCategory], [QuestionName], [CorrectAnswer], [QuestionLevel]) VALUES (48, N'Zespo³y', N'Nazwa której grupy muzycznej wziê³a siê od inicja³ów imion cz³onków zespo³u?', N'ABBA', 3)
INSERT [dbo].[Questions] ([QuestionId], [QuestionCategory], [QuestionName], [CorrectAnswer], [QuestionLevel]) VALUES (49, N'Zawód', N'Czym zajmuje siê barista?', N'Parzeniem kawy', 3)
INSERT [dbo].[Questions] ([QuestionId], [QuestionCategory], [QuestionName], [CorrectAnswer], [QuestionLevel]) VALUES (50, N'Zaufanie', N'Przedstawicielom której z wymienionych grup zawodowych Polacy ufaj¹ najbardziej?', N'Dziennikarzom', 3)
INSERT [dbo].[Questions] ([QuestionId], [QuestionCategory], [QuestionName], [CorrectAnswer], [QuestionLevel]) VALUES (51, N'Spo³eczeñstwo', N'W polsce ¿yje wiêcej:', N'Kobiet', 2)
INSERT [dbo].[Questions] ([QuestionId], [QuestionCategory], [QuestionName], [CorrectAnswer], [QuestionLevel]) VALUES (52, N'Seriale', N'Który serial widzowie zaczêli ogl¹daæ wczeœniej?', N'Domek na prerii', 2)
INSERT [dbo].[Questions] ([QuestionId], [QuestionCategory], [QuestionName], [CorrectAnswer], [QuestionLevel]) VALUES (53, N'Spo³eczeñstwo', N'Wiêkszoœæ Polek jest:', N'Po czterdziestce', 2)
INSERT [dbo].[Questions] ([QuestionId], [QuestionCategory], [QuestionName], [CorrectAnswer], [QuestionLevel]) VALUES (54, N'Sport', N'Jak d³ugo trwa³ najd³u¿szy mecz w historii zawodowego tenisa ziemnego?', N'6 godz. 11 minut', 2)
INSERT [dbo].[Questions] ([QuestionId], [QuestionCategory], [QuestionName], [CorrectAnswer], [QuestionLevel]) VALUES (55, N'Szk³o', N'Szk³o jest:', N'Cia³em sta³ym', 2)
INSERT [dbo].[Questions] ([QuestionId], [QuestionCategory], [QuestionName], [CorrectAnswer], [QuestionLevel]) VALUES (56, N'Ile wa¿y?', N'Ile, w przybli¿eniu, wa¿y ca³a dzisiejsza ludzkoœæ?', N'440 mln ton', 2)
INSERT [dbo].[Questions] ([QuestionId], [QuestionCategory], [QuestionName], [CorrectAnswer], [QuestionLevel]) VALUES (57, N'Internet', N'W którym roku uruchomiono pierwsz¹ stronê internetow¹?', N'1990', 2)
INSERT [dbo].[Questions] ([QuestionId], [QuestionCategory], [QuestionName], [CorrectAnswer], [QuestionLevel]) VALUES (58, N'Która m³odsza?', N'Która z tych gwiazd jest m³odsza?', N'Janet Jackson', 2)
INSERT [dbo].[Questions] ([QuestionId], [QuestionCategory], [QuestionName], [CorrectAnswer], [QuestionLevel]) VALUES (59, N'Kto na górze', N'Kto, wg Aleksandra Fredry, siedzia³ z wêdk¹ w komodzie?', N'Pawe³', 2)
INSERT [dbo].[Questions] ([QuestionId], [QuestionCategory], [QuestionName], [CorrectAnswer], [QuestionLevel]) VALUES (60, N'Wydarzenia', N'Co zdarzy³o siê wczeœniej', N'Pierwsza kobieta polecia³a w kosmos', 2)
GO
ALTER TABLE [dbo].[Answers]  WITH CHECK ADD  CONSTRAINT [FK_Answers_Questions] FOREIGN KEY([QuestionId])
REFERENCES [dbo].[Questions] ([QuestionId])
GO
ALTER TABLE [dbo].[Answers] CHECK CONSTRAINT [FK_Answers_Questions]
GO
